#include<iostream>
using namespace std;
int main(){
int a=-1;
int
try{
    if(a<0){
        throw a;
    }
}
catch(int a){
    cout<<"Catch Exception";
}




}
